plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from

  # Allows setting the H1 Markdown header as the page title.
  - jekyll-titles-from-headings

  # Allows per-post assets.
  - jekyll-postfiles

exclude:
  - third_party/

markdown: kramdown
highlighter: none
logo: false
permalink: pretty

language: "en"
timezone: "America/Los_Angeles"
title: "Jekyll Mini Theme"
description: "A mini Jekyll theme"
url: https://jekyll-mini.blogzhang.com

# jekyll-paginate-v2
pagination:
  enabled: true
  collection: 'posts'
  per_page: 15
  permalink: '/page/:num/'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layouts: ['collection.html']
    title: 'Tag :tag'
  collections:
    layouts: ['collection.html']
    title: 'Collection :col'
  categories:
    layouts: ['collection.html']
    title: 'Category :cat'

# jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
