name: Publish Blog

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish Blog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          token: ${{ secrets.TOKEN }}

      - uses: actions/cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.1.0
        with:
          token: ${{ secrets.TOKEN }}
          jekyll_src: '.'
          gem_src: '.'
