name: Publish Blog

on:
  push:
    branches: [ "main" ]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.TOKEN }}

      - uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - id: pages
        uses: actions/configure-pages@v5

      - run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

        # Automatically uploads an artifact from the './_site' directory by default
      - uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
